# Generated by Django 5.2.2 on 2025-06-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pendente', max_length=15),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservas.reservation')),
            ],
        ),
    ]
